### PR TITLE
IL-94 Feature MQTT client in the back-end

### PR DESCRIPTION
**Pull request by kjacmenja21**
This pull request aims to add handling of MQTT messages from a MQTT broker using the dependancy [FastApi-MQTT](https://sabuhish.github.io/fastapi-mqtt/).

The main feature of these changes is the `MQTTClientHandler`, which allows registration of per topic messsage handling. Using     `register_topic_handler()` method where passing a class that extends `MQTTTopicHandler` will register a new handler for messages of topic defined in `MQTTTopicHandler.topic`.

This will allow easy extending the existing code without the need to modify the base `MQTTClientHandler`.
Below is the example initialization and handler registration:

```python
@asynccontextmanager
async def lifespan(_: FastAPI):
    mqtt_client = MQTTClientHandler()
    await mqtt_client.start()
    mqtt_client.register_topic_handler(MQTTCoordinateHandler())

    yield

    await mqtt_client.stop()
```

### CODE REVIEW

**Review by jmojzes21 — CHANGES_REQUESTED** [review]
Are you sure that you want to merge this into **main branch**.

**Comment by kjacmenja21** [comment]
> Are you sure that you want to merge this into **main branch**?

What do you mean by this? Have I made a mistake @jmojzes21?

**Comment by kjacmenja21** [comment]
Ah! Noticed I am pushing to the wrong branch. Changed it from main to develop.

**Review by jmojzes21 — APPROVED** [review]
Great work. It's good to see that you use environment variables to read properties.

**Review by dsrecec20PRAVI — APPROVED** [review]
Great work!

**Review by MBesednik — APPROVED** [review]
It looks great!!

**Pull request merged**
